-- AI coach daily messages — one row per member per day.
-- Generated by /api/coach/daily (cron at 7am) or triggered manually.

create table public.coach_messages (
  id                 uuid primary key default uuid_generate_v4(),
  gym_id             uuid references public.gyms(id) on delete cascade not null,
  profile_id         uuid references public.profiles(id) on delete cascade not null,
  message            text not null,
  workout_summary    text,
  recovery_status    text check (recovery_status in ('good', 'low')),
  recommended_action text,
  streak_days        int not null default 1,
  message_date       date not null default current_date,
  created_at         timestamptz not null default now(),
  unique(profile_id, message_date)
);

alter table public.coach_messages enable row level security;

create policy "Gym owners view coach messages" on public.coach_messages
  using (gym_id in (select id from public.gyms where owner_id = auth.uid()));
